@startuml

entity Batch  {
    + forest_id
    + honey_id
}

entity BatchMember {
    + alphanum_code
    + batch_id
    + beekeeper_id
    + logo
    + external_url
}

entity Forest  {
  + title
  + map_kml
  + description
  + photo
  + area
  + animals
  + beekeepers_count
  + plants
}

entity Beekeeper  {
  + name
  + bio
  + photo
  + letter_text
  + letter_photo
  --
}

entity Honey  {
  + name
  + variety
  + honey_text
  + jar_photo
  + harvest_photo
  + honey_description
  + harvest_description
  + health_description
  --
}


Batch -down-|{ BatchMember
Forest -down-o{ Batch
Honey -down-o{ Batch
Beekeeper -down-o{ BatchMember


@enduml
