@startuml

entity Batch  {
}

entity BatchMember {
    + alphanum_code
    + batch
    + beekeeper
}

entity Forest  {
  + forest_title
  + map_url
  + description
  + image_url
  + area
  + animals
  + beekeepers_num
  + plants
}

entity Beekeeper  {
  + name
  + bio
  + image_url
  + letter_text
  + letter_img_url
  --
}

entity Honey  {
  + name
  + variety
  + honey_text
  + jar_img_url
  + harvest_img_url
  + harvest_text
  + health_text
  --
}


Batch -down-|{ BatchMember
Forest -down-o{ Batch
Honey -down-o{ Batch
Beekeeper -down-o{ BatchMember


@enduml
