# Generated by Django 3.0.7 on 2020-06-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('image_url', models.URLField()),
                ('letter_text', models.TextField()),
                ('letter_img_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('map_url', models.URLField(help_text='Google map url')),
                ('description', models.TextField()),
                ('image_url', models.URLField(help_text='Forest image url')),
                ('area', models.CharField(help_text='Forest area', max_length=50)),
                ('animals', models.CharField(help_text='Forest animals', max_length=50)),
                ('beekeepers_num', models.CharField(help_text='Number of beekeepers', max_length=50)),
                ('plants', models.CharField(help_text='Forest plants', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Honey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('jar_img_url', models.URLField(help_text='Forest image url')),
                ('harvest_img_url', models.URLField(help_text='Forest image url')),
                ('honey_description', models.TextField(help_text='Honey description')),
                ('harvest_description', models.TextField(help_text='Harvest description')),
                ('health_description', models.TextField(help_text='Health description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphanum_code', models.CharField(help_text='Alphanumeric Code', max_length=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Batch')),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Beekeeper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='forest',
            field=models.ForeignKey(blank=True, help_text='Forest that Batch came from, optional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Forest'),
        ),
        migrations.AddField(
            model_name='batch',
            name='honey',
            field=models.ForeignKey(blank=True, help_text='Batch honey, optional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Honey'),
        ),
    ]
