# Generated by Django 3.0.7 on 2020-06-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('alphanum_code', models.CharField(help_text='Alphanumeric Code', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='BeekeeperTeam',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('map_url', models.URLField(help_text='Google map url')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('image_url', models.URLField()),
                ('letter_text', models.TextField()),
                ('letter_img_url', models.URLField()),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.BeekeeperTeam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchMember',
            fields=[
                ('_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Batch')),
                ('beekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Beekeeper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='forest',
            field=models.ForeignKey(blank=True, help_text='Forest that Batch came from, optional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Forest'),
        ),
        migrations.AddField(
            model_name='batch',
            name='health',
            field=models.ForeignKey(blank=True, help_text='Batch health, optional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Health'),
        ),
    ]
