# Generated by Django 3.0.7 on 2020-06-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honey',
            options={'verbose_name_plural': 'honey'},
        ),
        migrations.RemoveField(
            model_name='forest',
            name='beekeepers_num',
        ),
        migrations.AddField(
            model_name='forest',
            name='beekeeper_count',
            field=models.IntegerField(default=0, help_text='Number of beekeepers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchmember',
            name='alphanum_code',
            field=models.CharField(help_text='Alphanumeric Code', max_length=15, unique=True),
        ),
    ]
