# Generated by Django 3.0.7 on 2020-06-22 17:57

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beekeeper',
            name='photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
