# Generated by Django 3.0.7 on 2020-06-23 14:08

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200623_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmember',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchmember',
            name='photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
