# Generated by Django 3.0.7 on 2020-06-24 19:03

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200623_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchmember',
            old_name='photo',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='beekeeper',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='beekeeper',
            name='letter_img_url',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='forest',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='honey',
            name='harvest_img_url',
        ),
        migrations.RemoveField(
            model_name='honey',
            name='jar_img_url',
        ),
        migrations.AddField(
            model_name='beekeeper',
            name='letter_photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='forest',
            name='map_kml',
            field=models.FileField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='forest',
            name='photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='honey',
            name='harvest_photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='honey',
            name='jar_photo',
            field=web.models.CustomImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
