# Generated by Django 3.0.7 on 2020-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200624_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='area',
            field=models.IntegerField(help_text='Forest area'),
        ),
    ]
